version: 0.2

phases:
  install:
      commands:
      # Install Terraform
      - echo "Installing Terraform..."
      - rm -rf terraform  # Remove any existing directory named 'terraform'
      - curl -O https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
      - unzip terraform_1.4.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version  # Confirm Terraform installation
  pre_build:
    commands:
      - echo "Checking current directory and listing files..."
      - pwd  # Print working directory
      - ls -la  # List all files and directories
      - ls -la terraform/environments  # Check if 'terraform/environments/test' exists

      # Navigate to the Terraform directory
      - cd tf/environments/test
      - terraform init
      - terraform plan
  build:
    commands:
      - terraform apply --auto-approve
artifacts:
  files:
    - '**/*'
