version: 0.2

phases:
  install:
    commands:
      # Install kubectl
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
  build:
    commands:
      - echo "Running tests..."
      - aws eks update-kubeconfig --region eu-west-3 --name webservice-cluster --alias webservice-cluster
      - kubectl get pods --namespace default | grep wordpress
      - export LOAD_BALANCER_URL=$(kubectl get svc -n default -l app.kubernetes.io/name=wordpress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
      - curl -I http://$LOAD_BALANCER_URL:8080/wp-login.php