version: 0.2

phases:
  pre_build:
    commands:
      - cd terraform/environments/test
      - terraform init
      - terraform plan
  build:
    commands:
      - terraform apply --auto-approve
artifacts:
  files:
    - '**/*'
