version: 0.2

phases:
  install:
    commands:
    # Install Helm
      - echo "Installing Helm..."
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version  # Confirm Helm installation

    # Install kubectl
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client  # Confirm kubectl installation
  pre_build:
    commands:
      - echo "Configuring kubectl for EKS..."
      - aws eks update-kubeconfig --region eu-west-3 --name webservice-cluster --alias webservice-cluster
      - kubectl create namespace monitoring || echo "Namespace 'monitoring' already exists"
  build:
    commands:
      - echo "Ajout des repos Helm pour Prometheus and Grafana..."
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo add grafana https://grafana.github.io/helm-charts
      - helm repo update
      
      - echo "Deploying Prometheus..."
      - helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring
      
      - echo "Deploying Grafana..."
      - helm upgrade --install grafana grafana/grafana --namespace monitoring --set adminPassword='admin'
  post_build:
    commands:
      - echo "Prometheus and Grafana deployed successfully."
      - export GRAFANA_URL=$(kubectl get svc --namespace monitoring grafana -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
      - echo "Grafana URL: http://$GRAFANA_URL"
artifacts:
  files:
    - "**/*"
  discard-paths: yes
