version: 0.2

phases:
  pre_build:
    commands:
      - cd terraform/environments/test
      - terraform init
      - terraform plan
  build:
    commands:
      - echo "Lancement du Terraform Apply...""
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform deploiement terminé."
artifacts:
  files:
    - '**/*'
