version: 0.2

phases:
install:
    commands:
    # Install Helm
      - echo "Installing Helm..."
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version  # Confirm Helm installation

    # Install kubectl
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client  # Confirm kubectl installation
pre_build:
    commands:
      - aws eks update-kubeconfig --region eu-west-3 --name webservice-cluster --alias webservice-cluster
build:
    commands:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo add grafana https://grafana.github.io/helm-charts
      - helm repo update
      - kubectl create namespace monitoring
      - helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
      - helm install grafana grafana/grafana --namespace monitoring
