version: 0.2

phases:
  install:
    commands:
    # Install Helm
      - echo "Installing Helm..."
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version  # Confirm Helm installation

    # Install kubectl
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client  # Confirm kubectl installation
  pre_build:
    commands:
      - aws eks update-kubeconfig --region eu-west-3 --name webservice-cluster --alias webservice-cluster
      - aws iam attach-role-policy --role-name EKSNodeGroupRole-webservice-cluster-dev --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  build:
    commands:
      - helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      - helm repo update
      - helm upgrade --install aws-ebs-csi-driver --namespace kube-system aws-ebs-csi-driver/aws-ebs-csi-driver
      - helm upgrade --install wordpress kube/wordpress-chart -f kube/wordpress-values.yaml --namespace default --set image.repository=654654192380.dkr.ecr.eu-west-3.amazonaws.com/webservice-ecr,image.tag=latest
